install.packages("rvest", repos="https://cloud.r-project.org/")
install.packages("devtools", repos="https://cloud.r-project.org/")
devtools::install_github("s-u/unixtools")
install.packages("reticulate", repos="https://cloud.r-project.org/")
install.packages("tensorflow", repos="https://cloud.r-project.org/")
#tensorflow::install_tensorflow(version = "2.0.0")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")


install.packages("keras", repos="https://cloud.r-project.org/")
#keras::install_keras()
install.packages("Rcpp", repos="https://cloud.r-project.org/")
install.packages("tidyr", repos="https://cloud.r-project.org/")
install.packages("leaflet", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("lubridate", repos="https://cloud.r-project.org/")
install.packages("rmarkdown", repos="https://cloud.r-project.org/")
install.packages("hexbin", repos="https://cloud.r-project.org/")
install.packages("penalized", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")


install.packages("httr", repos="https://cloud.r-project.org/")
install.packages("httpuv", repos="https://cloud.r-project.org/")
install.packages("DT", repos="https://cloud.r-project.org/")
install.packages("magrittr", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ggplot2", repos="https://cloud.r-project.org/")
install.packages("gridExtra", repos="https://cloud.r-project.org/")
install.packages("bitops", repos="https://cloud.r-project.org/")
install.packages("reactable", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("remotes", repos="https://cloud.r-project.org/")
install.packages("shiny", repos="https://cloud.r-project.org/")
install.packages("knitr", repos="https://cloud.r-project.org/")
install.packages("sparklyr", repos="https://cloud.r-project.org/")
sparklyr::spark_install()

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")


install.packages("tfautograph", repos="https://cloud.r-project.org/")
install.packages("nycflights13", repos="https://cloud.r-project.org/")
install.packages("Lahman", repos="https://cloud.r-project.org/")
install.packages("rsparkling", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("h2o", repos="https://cloud.r-project.org/")
install.packages("rscala", repos="https://cloud.r-project.org/")
install.packages("shinydashboard", repos="https://cloud.r-project.org/")
install.packages("learnr", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("here", repos="https://cloud.r-project.org/")
install.packages("ctv", repos="https://cloud.r-project.org/")
install.packages("evtree", repos="https://cloud.r-project.org/")
install.packages("mokken", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("lvnet", repos="https://cloud.r-project.org/")
install.packages("randomForestSRC", repos="https://cloud.r-project.org/")
install.packages("GeneNet", repos="https://cloud.r-project.org/")
install.packages("sna", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("abc", repos="https://cloud.r-project.org/")
install.packages("radiant", repos="https://cloud.r-project.org/")
install.packages("radiant.data", repos="https://cloud.r-project.org/")
install.packages("radiant.design", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("radiant.basics", repos="https://cloud.r-project.org/")
install.packages("radiant.model", repos="https://cloud.r-project.org/")
install.packages("radiant.multivariate", repos="https://cloud.r-project.org/")
install.packages("rcc", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("RGCCA", repos="https://cloud.r-project.org/")
install.packages("ggquickeda", repos="https://cloud.r-project.org/")
install.packages("openintro", repos="https://cloud.r-project.org/")
install.packages("effects", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("Rborist", repos="https://cloud.r-project.org/")
install.packages("rbartMachine", repos="https://cloud.r-project.org/")
devtools::install_github("sachsmc/ggkm")
devtools::install_github("benjaminrich/table1")
devtools::install_github("slowkow/ggrepel")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("hdi", repos="https://cloud.r-project.org/")
install.packages("tfplot", repos="https://cloud.r-project.org/")
install.packages("ranger", repos="https://cloud.r-project.org/")
install.packages("purr", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("tfruns", repos="https://cloud.r-project.org/")
install.packages("tfprobability", repos="https://cloud.r-project.org/")
install.packages("tframe", repos="https://cloud.r-project.org/")
install.packages("reticulate", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("tfestimators", repos="https://cloud.r-project.org/")
install.packages("sem", repos="https://cloud.r-project.org/")
install.packages("glmnet", repos="https://cloud.r-project.org/")
install.packages("mirt", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("BayesTree", repos="https://cloud.r-project.org/")
install.packages("BayesTreePrior", repos="https://cloud.r-project.org/")
install.packages("mlpack", repos="https://cloud.r-project.org/")
install.packages("mboost", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("readr", repos="https://cloud.r-project.org/")
install.packages("callr", repos="https://cloud.r-project.org/")
install.packages("jpeg", repos="https://cloud.r-project.org/")
install.packages("lavaan", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("blavaan", repos="https://cloud.r-project.org/")
install.packages("semTools", repos="https://cloud.r-project.org/")
install.packages("ipred", repos="https://cloud.r-project.org/")
install.packages("rprojroot", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ipred", repos="https://cloud.r-project.org/")
install.packages("wsrf", repos="https://cloud.r-project.org/")
install.packages("ergm", repos="https://cloud.r-project.org/")
install.packages("np", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("lasso2", repos="https://cloud.r-project.org/")
install.packages("lars", repos="https://cloud.r-project.org/")
install.packages("DescTools", repos="https://cloud.r-project.org/")
install.packages("MCMCpack", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("caTools", repos="https://cloud.r-project.org/")
install.packages("mlr3", repos="https://cloud.r-project.org/")
install.packages("mlr3benchmark", repos="https://cloud.r-project.org/")
install.packages("mlr3cluster", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("mlr3data", repos="https://cloud.r-project.org/")
install.packages("mlr3db", repos="https://cloud.r-project.org/")
install.packages("mlr3filters", repos="https://cloud.r-project.org/")
install.packages("mlr3fselect", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("mlr3hyperband", repos="https://cloud.r-project.org/")
install.packages("mlr3learners", repos="https://cloud.r-project.org/")
install.packages("mlr3measures", repos="https://cloud.r-project.org/")
install.packages("mlr3misc", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("mlr3oml", repos="https://cloud.r-project.org/")
install.packages("mlr3pipelines", repos="https://cloud.r-project.org/")
install.packages("mlr3poba", repos="https://cloud.r-project.org/")
install.packages("mlr3shiny", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("mlr3spatiotempcv", repos="https://cloud.r-project.org/")
install.packages("mlr3tuning", repos="https://cloud.r-project.org/")
install.packages("mlr3verse", repos="https://cloud.r-project.org/")
install.packages("mlr3viz", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

ctv::install.views("TimeSeries", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ahaz" , repos="https://cloud.r-project.org/")
install.packages("arules", repos="https://cloud.r-project.org/")
install.packages("BART", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("bartMachine", repos="https://cloud.r-project.org/")
install.packages("BayesTree", repos="https://cloud.r-project.org/")
install.packages("BDgraph", repos="https://cloud.r-project.org/")
install.packages("biglasso", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("bmrm", repos="https://cloud.r-project.org/")
install.packages("Boruta", repos="https://cloud.r-project.org/")
install.packages("bst", repos="https://cloud.r-project.org/")
install.packages("C50", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("caret", repos="https://cloud.r-project.org/")
install.packages("CORElearn", repos="https://cloud.r-project.org/")
install.packages("Cubist", repos="https://cloud.r-project.org/")
install.packages("deepnet", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("DoubleML", repos="https://cloud.r-project.org/")
install.packages("e1071", repos="https://cloud.r-project.org/")
install.packages("earth", repos="https://cloud.r-project.org/")
install.packages("effects", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("elasticnet", repos="https://cloud.r-project.org/")
install.packages("evclass", repos="https://cloud.r-project.org/")
install.packages("frbs", repos="https://cloud.r-project.org/")
install.packages("gamboostLSS", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("gbm", repos="https://cloud.r-project.org/")
install.packages("ggRandomForests", repos="https://cloud.r-project.org/")
install.packages("glmnet", repos="https://cloud.r-project.org/")
install.packages("glmpath", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("GMMBoost", repos="https://cloud.r-project.org/")
install.packages("gradDescent", repos="https://cloud.r-project.org/")
install.packages("grf", repos="https://cloud.r-project.org/")
install.packages("grplasso", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("grpreg", repos="https://cloud.r-project.org/")
install.packages("hda", repos="https://cloud.r-project.org/")
install.packages("hdi", repos="https://cloud.r-project.org/")
install.packages("hdm", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ICEbox", repos="https://cloud.r-project.org/")
install.packages("kernlab", repos="https://cloud.r-project.org/")
install.packages("klaR", repos="https://cloud.r-project.org/")
install.packages("LiblineaR", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("lightgbm", repos="https://cloud.r-project.org/")
install.packages("maptree", repos="https://cloud.r-project.org/")
install.packages("mlpack", repos="https://cloud.r-project.org/")
install.packages("naivebayes", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ncvreg", repos="https://cloud.r-project.org/")
install.packages("nnet", repos="https://cloud.r-project.org/")
install.packages("OneR", repos="https://cloud.r-project.org/")
install.packages("opusminer", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("pamr", repos="https://cloud.r-project.org/")
install.packages("party", repos="https://cloud.r-project.org/")
install.packages("partykit", repos="https://cloud.r-project.org/")
install.packages("pdp", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("penalized", repos="https://cloud.r-project.org/")
install.packages("penalizedLDA", repos="https://cloud.r-project.org/")
install.packages("picasso", repos="https://cloud.r-project.org/")
install.packages("plotmo", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("quantregForest", repos="https://cloud.r-project.org/")
install.packages("randomForest", repos="https://cloud.r-project.org/")
install.packages("randomForestSRC", repos="https://cloud.r-project.org/")
install.packages("missRanger", repos="https://cloud.r-project.org/")
install.packages("rattle", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("Rborist", repos="https://cloud.r-project.org/")
install.packages("RcppDL", repos="https://cloud.r-project.org/")
install.packages("rdetools", repos="https://cloud.r-project.org/")
install.packages("relaxo", repos="https://cloud.r-project.org/")
install.packages("rgenoud", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("RGF", repos="https://cloud.r-project.org/")
install.packages("RLT", repos="https://cloud.r-project.org/")
install.packages("Rmalschains", repos="https://cloud.r-project.org/")
install.packages("rminer", repos="https://cloud.r-project.org/")
install.packages("ROCR", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("RoughSets", repos="https://cloud.r-project.org/")
install.packages("rpart", repos="https://cloud.r-project.org/")
install.packages("RPMM", repos="https://cloud.r-project.org/")
install.packages("RSNNS", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("RWeka", repos="https://cloud.r-project.org/")
install.packages("RXshrink", repos="https://cloud.r-project.org/")
install.packages("sda", repos="https://cloud.r-project.org/")
install.packages("SIS", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("splitTools", repos="https://cloud.r-project.org/")
install.packages("ssgraph", repos="https://cloud.r-project.org/")
install.packages("stabs", repos="https://cloud.r-project.org/")
install.packages("SuperLearner", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("svmpath", repos="https://cloud.r-project.org/")
install.packages("tgp", repos="https://cloud.r-project.org/")
install.packages("torch", repos="https://cloud.r-project.org/")
install.packages("tree", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("trtf", repos="https://cloud.r-project.org/")
install.packages("varSelRF", repos="https://cloud.r-project.org/")
install.packages("wsrf", repos="https://cloud.r-project.org/")
install.packages("xgboost", repos="https://cloud.r-project.org/")
# 
# # ctv::install.views("MachineLearning", repos="https://cloud.r-project.org/")
# 
# require(unixtools)
# path<-tempdir()
# system(paste("rm -rf ", path, sep=""))
# system("mkdir /tmp/new_tmp")
# set.tempdir("/tmp/new_tmp")